feat(anti-addiction): update REST API
taptap/tds-docs pull request #128
Opened 2022-04-14 03:56 UTC by kylinbin

同步更新 [防沉迷服务新REST API接口](https://confluence.xindong.com/pages/viewpage.action?pageId=638151014)](https://confluence.xindong.com/pages/viewpage.action?pageId=638151014)。

并做了以下调整：
- 几个接口的顺序从「上报消费金额 - 检查消费是否受限 - 检查玩家当前能否游戏」改为「检查玩家当前能否游戏 - 检查消费是否受限 - 上报消费金额」，感觉更符合开发者使用顺序。
- 接口示例改为 cURL 命令，已经自己试用过没有问题。近期有一个[工单](https://dc.leanticket.cn/tickets/9556)，就是开发者没看明白 token 怎么放（说实话我也迷惑了一会儿），所以不如用更清晰的 cURL。
- 请求的 url 中 `userId` 改为 `userIdentifier`，因为整篇文档都在用 `userIdentifier` 这个说法，没必要再加一个 `userId`，多一个词就多一种解释也多了一点麻烦。

2022-04-16 10:48 UTC, QuantumBear commented on docs/sdk/anti-addiction/guide.mdx
> +实名认证失败（包括 Token 解析错误）时返回 401 错误：
实名认证Token解析错误时返回401错误，而实名认证失败是，返回HTTP status code依然是200，内容如下：
```json
{
    "success": true,
    "data": {
        "status": 2,
        "anti_addiction_token": "",
        "age_limit": 18,
        "has_auth_record": false
    }
}
```

2022-04-18 06:14 UTC, fuchenshi requested changes

2022-04-18 06:14 UTC, fuchenshi commented on docs/sdk/anti-addiction/guide.mdx
> +        "msg":"该账号没有通过实名认证"}
```suggestion
        "msg":"该账号没有通过实名认证"
```

2022-04-18 06:58 UTC, fuchenshi approved these changes

2022-04-18 07:00 UTC, merged