docs: TapTap 登录添国际化接口说明
taptap/tds-docs pull request #138
Opened 2022-05-05 09:11 UTC by WatchMan-Wang

2022-05-05 09:23 UTC, fuchenshi approved these changes

2022-05-05 09:25 UTC, fuchenshi requested changes

2022-05-05 09:25 UTC, fuchenshi commented on docs/sdk/taptap-login/guide/start.mdx
> +<Languages />
`Languages` 没在文档开头引用。

2022-05-05 09:43 UTC, kylinbin commented
上下文见 [slack 讨论](https://xindong.slack.com/archives/C01HZ8BS7PT/p1651639963997219)。

2022-05-05 10:13 UTC, fuchenshi requested changes

2022-05-05 10:13 UTC, fuchenshi commented on docs/sdk/taptap-login/guide/start.mdx
> +import Languages from '../_partials/languages.mdx';
```suggestion
import Languages from '../../_partials/languages.mdx';
```

2022-05-05 10:13 UTC, kylinbin commented on docs/sdk/taptap-login/guide/start.mdx
> +import Languages from '../_partials/languages.mdx';
预览挂了，是这个路径有问题吧

2022-05-07 09:46 UTC, fuchenshi approved these changes

2022-05-07 09:46 UTC, merged