1、更正 PHP 代码示例 2、登录增加 FQA
taptap/tds-docs pull request #194
Opened 2022-06-29 03:30 UTC by WatchMan-Wang

1、更正 PHP 代码示例 2、登录增加 FQA 3、将 FQA 代码量大的采用折叠方式展现

2022-06-29 03:36 UTC, kylinbin commented on docs/sdk/start/faq.mdx
> +### TapTap 登录报： signature not match 异常。
```suggestion
### TapTap 登录报 signature not match 异常
```

2022-06-29 03:39 UTC, kylinbin commented on docs/sdk/start/faq.mdx
> +TapTap [开发者中心应用](https://developer.taptap.com/docs/sdk/start/quickstart/#配置签名证书)没有配置 MD5 或者配置错了 MD5 都会提示改异常。有的开发者可能没有调试出异常信息，可以通过这种方式进行验证：如果将 TapTap 客户端卸载，进行登录功能时会弹出 Web 页形式进行授权，如果可以授权成功，而安装了 TapTap
```suggestion
接入了 TapTap 登录但没有在开发者中心后台配置签名或者配置错了都会提示该异常。有的开发者可能没有调试出异常信息，可以通过这种方式进行验证：如果将 TapTap 客户端卸载，测试登录功能时会弹出 WebView 授权，而测试设备安装了 TapTap 客户端则无法拉起客户端授权，这种情况基本上就是因为签名配置问题导致的，请参考[文档](/sdk/start/quickstart/#配置签名证书)完成配置。
```

2022-06-29 03:39 UTC, kylinbin commented on docs/sdk/start/faq.mdx
> +### TapTap 登录提示：抱歉，该游戏/应用暂未开放
```suggestion
### TapTap 登录提示「抱歉，该游戏/应用暂未开放」
```

2022-06-29 03:42 UTC, kylinbin commented on docs/sdk/start/faq.mdx
> +游戏正式上线之前没有开启「开放全量用户」同时也没有[添加用户管理](https://developer.taptap.com/docs/sdk/start/test-accounts/)时测试 TapTap 登录则会出现该提示。解决方案：选择「测试用户管理」，进入页面，点击「添加用户」按钮。填写用户 ID 也就是 TapTap 客户端或昵称搜索用户，选择用户并提交，成功将用户添加进名单。
```suggestion
游戏正式上线之前没有在 **游戏服务 > 生态服务 > TapTap 登录** 处开启「开放全量用户」同时也没有[添加测试用户](/sdk/start/test-accounts/)时测试 TapTap 登录则会出现该提示。

解决方案：游戏还在测试阶段，可以选择「测试用户管理」，进入页面，点击「添加用户」按钮。根据用户 ID 或昵称搜索，将其添加进测试用户名单。

在游戏上线时，点击「开放全量用户」。
```

2022-06-29 07:53 UTC, fuchenshi requested changes

2022-06-29 07:53 UTC, fuchenshi commented on docs/sdk/start/faq.mdx
> +<summary>build.gradle 的p配置</summary>
```suggestion
<summary>build.gradle 的配置</summary>
```

2022-06-30 02:38 UTC, kylinbin approved these changes

2022-06-30 02:52 UTC, merged