add billboard design guideline（include English docs）
taptap/tds-docs pull request #206
Opened 2022-07-21 09:34 UTC by SXiaoXu

2022-07-21 11:02 UTC, SXiaoXu commented
上下文见[这里](https://xindong.slack.com/archives/C03HJFMQ65B/p1658396656954199?thread_ts=1657780644.254419&cid=C03HJFMQ65B)。

2022-07-22 05:52 UTC, fuchenshi requested changes

2022-07-22 05:52 UTC, fuchenshi commented on i18n/en/docusaurus-plugin-content-docs/current/design/design-billboard.mdx
> +    quote="correct back to previous level button"
```suggestion
    quote="Correct back to previous level button"
```

2022-07-22 05:52 UTC, fuchenshi commented on i18n/en/docusaurus-plugin-content-docs/current/design/design-billboard.mdx
> +### Horizontal screen configuration cut size
横屏/竖屏一般会说 landscape/portrait。

2022-07-27 07:54 UTC, fuchenshi approved these changes

2022-07-27 07:54 UTC, merged