feat: billboard
taptap/tds-docs pull request #221
Opened 2022-08-02 03:48 UTC by kylinbin

2022-08-02 05:45 UTC, kylinbin commented on docs/sdk/billboard/guide.mdx
> +* 使用 TDS 公告服务之前，需要在开发者中心后台 > 游戏服务 > 应用配置 > 公告系统 处开通服务。
```suggestion
接入 TDS 公告服务 SDK 之前，请参考[《功能介绍》文档](/sdk/billboard/features/#功能介绍)完成**服务开通、域名配置、模板配置和维度配置**。
```

感觉接公告的前置条件比较多，仅仅开通是不够的，改成这样可以吗？

2022-08-02 05:56 UTC, kylinbin commented on docs/sdk/billboard/guide.mdx
> +        .RegionType(isCN ? RegionType.CN : RegionType.IO) // 可选项，CN 表示中国大陆，IO 表示其他国家或地区
```suggestion
        .RegionType(RegionType.CN) // 可选项，CN 表示中国大陆，IO 表示其他国家或地区
```

这个 isCN 是哪里来的，开发者希望直接复制就能用的话，是不是改成上面这样更方便？

2022-08-02 05:56 UTC, kylinbin commented on docs/sdk/billboard/guide.mdx
> +var billboardServerUrl = "xxx";
```suggestion
var billboardServerUrl = "https://your-billboard-server-url"; // 开发者中心 > 你的游戏 > 游戏服务 > 应用配置 > 域名配置 > 公告
```

域名配置的问题/工单会非常多，所以先写得明显一点、防止开发者填错？

2022-08-02 05:56 UTC, kylinbin commented on docs/sdk/billboard/guide.mdx
> +// 海外参数初始化
国内海外，我分开写吧，按照开发者复制的习惯，会一次性全复制了，容易弄混。

2022-08-02 05:56 UTC, kylinbin commented on docs/sdk/billboard/guide.mdx
> +
初始化这里各种参数很多，需要加参数说明，我等会线下再确认一下。

另外还有个问题就是，这里的初始化和快速开始部分的初始化之间有什么关系，开发者接入多种服务的时候怎么取舍

2022-08-02 05:56 UTC, kylinbin commented on docs/sdk/billboard/guide.mdx
> +        // 打开公告失败  可以根据 error.code 和 error.errorDescription 来判断错误原因
具体的 code 和 description 可以在下面列出来吗？或者给我个对应代码的链接，我来写。

2022-08-02 05:56 UTC, kylinbin commented on docs/sdk/billboard/guide.mdx
> +        // 获取小红点信息失败 可以根据 error.code 和 error.errorDescription 来判断错误原因
同上，code 和 description 最好列出来。

2022-08-02 05:56 UTC, kylinbin commented on docs/sdk/billboard/guide.mdx
> +当游戏发布的公告配置的跳转链接为「游戏内模块」，或者游戏正文添加了链接并且链接类型为「游戏内模块」的时候。可以通过监听自定义事件来获取消息，并做相应处理。
这一句我看不懂……

2022-08-02 05:56 UTC, kylinbin commented on docs/sdk/billboard/guide.mdx
> +    // 这里返回的 url 地址和游戏在公告系统内配置的地址是一致的
再明确一下，就是公告域名的意思吗

2022-08-02 06:11 UTC, kylinbin commented on docs/sdk/billboard/guide.mdx
> +当游戏发布的公告配置的跳转链接为「游戏内模块」，或者游戏正文添加了链接并且链接类型为「游戏内模块」的时候。可以通过监听自定义事件来获取消息，并做相应处理。
看了功能介绍好像懂一点了，这里需要加点说明 🤔

2022-08-02 06:47 UTC, fuchenshi requested changes

2022-08-02 06:47 UTC, fuchenshi commented on docs/sdk/billboard/guide.mdx
> +                "jump_link": "https://www.baidu.com",
这里的示例链接用百度官网会不会显得太随意…

2022-08-02 07:13 UTC, JingPig1021 commented on docs/sdk/billboard/guide.mdx
> +当游戏发布的公告配置的跳转链接为「游戏内模块」，或者游戏正文添加了链接并且链接类型为「游戏内模块」的时候。可以通过监听自定义事件来获取消息，并做相应处理。
如果功能介绍页看不懂的话，我也可以改

2022-08-02 07:37 UTC, hexinghuaxd commented on docs/sdk/billboard/guide.mdx
> +        .RegionType(isCN ? RegionType.CN : RegionType.IO) // 可选项，CN 表示中国大陆，IO 表示其他国家或地区
isCN 是需要开发者定义的，的确你的写法更好一点

2022-08-02 07:38 UTC, hexinghuaxd commented on docs/sdk/billboard/guide.mdx
> +var billboardServerUrl = "xxx";
👌

2022-08-02 07:39 UTC, hexinghuaxd commented on docs/sdk/billboard/guide.mdx
> +    // 这里返回的 url 地址和游戏在公告系统内配置的地址是一致的
不是，是内部模块跳转链接的地址

2022-08-02 07:43 UTC, JingPig1021 commented on docs/sdk/billboard/guide.mdx
> +* 使用 TDS 公告服务之前，需要在开发者中心后台 > 游戏服务 > 应用配置 > 公告系统 处开通服务。
前置条件只需要写到「开通服务」「域名配置（仅国内）」就行，「模版配置」和「维度配置」开发者是可以不配的

2022-08-02 07:44 UTC, JingPig1021 commented on docs/sdk/billboard/guide.mdx
> +                "jump_link": "https://www.baidu.com",
那就用 https://www.taptap.com  呗

2022-08-02 07:52 UTC, hexinghuaxd commented on docs/sdk/billboard/guide.mdx
> +// 海外参数初始化
👌

2022-08-02 07:52 UTC, hexinghuaxd commented on docs/sdk/billboard/guide.mdx
> +        // 打开公告失败  可以根据 error.code 和 error.errorDescription 来判断错误原因
`code` | 场景
 --- | ---
 19999 | 其它错误，内容可以参考description
 50x 的服务器错误 | 服务端内部错误
 401 | 未授权（可以检查初始化配置的参数是否正确配置）
 403 | 用户无权限访问该服务（检查开发者中心是否开通了TapPayment服务）

2022-08-02 09:30 UTC, kylinbin commented on docs/sdk/billboard/guide.mdx
> +// highlight-start
为了和快速开始的初始化好好相处，加了一些高亮，现在预览不太好看，呼唤 @fuchenshi 有空装修一下：https://docusaurus.io/docs/markdown-features/code-blocks#line-highlighting

2022-08-02 09:44 UTC, kylinbin commented on docs/sdk/billboard/guide.mdx
> +[TapBootstrap initWithConfig:config];
iOS SDK 的初始化没用到 `billboardCnConfig`， @hexinghuaxd 看这里 👀

2022-08-02 09:45 UTC, kylinbin commented on docs/sdk/billboard/guide.mdx
> +NSMutableSet &lt;NSArray *&gt; *dimensionSet = [[NSMutableSet alloc] init];
这行是正常的吗，感觉混入了乱码 @hexinghuaxd

2022-08-02 10:00 UTC, fuchenshi commented on docs/sdk/billboard/guide.mdx
> +// highlight-start
https://github.com/taptap/tds-docs/pull/222

2022-08-03 02:40 UTC, hexinghuaxd commented on docs/sdk/billboard/guide.mdx
> +NSMutableSet &lt;NSArray *&gt; *dimensionSet = [[NSMutableSet alloc] init];
“&lt” 对应 "<" 
“&gt” 对应 “>”

2022-08-03 02:43 UTC, hexinghuaxd commented on docs/sdk/billboard/guide.mdx
> +[TapBootstrap initWithConfig:config];
嗯 需要在 [TapBootstrap initWithConfig:config]; 前加一句 config.tapBillboardConfig = billboardConfig;

2022-08-03 02:43 UTC, fuchenshi requested changes

2022-08-03 02:43 UTC, fuchenshi commented on docs/sdk/billboard/guide.mdx
> +NSMutableSet &lt;NSArray *&gt; *dimensionSet = [[NSMutableSet alloc] init];
```suggestion
NSMutableSet <NSArray *> *dimensionSet = [[NSMutableSet alloc] init];
```

2022-08-03 02:43 UTC, fuchenshi commented on docs/sdk/billboard/guide.mdx
> +NSMutableSet &lt;NSArray *&gt; *dimensionSet = [[NSMutableSet alloc] init];
```suggestion
NSMutableSet <NSArray *> *dimensionSet = [[NSMutableSet alloc] init];
```

2022-08-03 04:16 UTC, fuchenshi commented on docs/sdk/billboard/guide.mdx
> +Pair<string, string> location = new Pair<string, string>("location", "TW");
示例代码的 `location` 要不要写成 `CN`？

2022-08-03 04:33 UTC, fuchenshi requested changes

2022-08-03 04:33 UTC, fuchenshi commented on docs/sdk/billboard/guide.mdx
> +* `dimensionSet` 参考[公告系统维度配置](sdk/billboard/features/#维度配置)，这里使用了两个预设维度：渠道（platform）和地区（location）。
```suggestion
* `dimensionSet` 参考[公告系统维度配置](/sdk/billboard/features/#维度配置)，这里使用了两个预设维度：渠道（platform）和地区（location）。
```

2022-08-03 04:33 UTC, fuchenshi commented on docs/sdk/billboard/guide.mdx
> +        // 打开公告失败，可以根据 TapBillboardException.code 和 TapBillboardException.message 来判断错误原因
```suggestion
        // 打开公告失败，可以根据 tapBillboardException.code 和 tapBillboardException.message 来判断错误原因
```

2022-08-03 04:33 UTC, fuchenshi commented on docs/sdk/billboard/guide.mdx
> +        // 获取小红点信息失败 可以根据 TapBillboardException.code 和 TapBillboardException.message 来判断错误原因
```suggestion
        // 获取小红点信息失败 可以根据 tapBillboardException.code 和 tapBillboardException.message 来判断错误原因
```

2022-08-03 04:33 UTC, fuchenshi commented on docs/sdk/billboard/guide.mdx
> +当[游戏发布的公告配置的跳转链接为「游戏内模块」](/sdk/billboard/features/#发布公告)，或者游戏正文添加了链接并且链接类型为「游戏内模块」的时候。可以通过监听自定义事件来获取消息，并做相应处理。
```suggestion
当[游戏发布的公告配置的跳转链接为「游戏内模块」](/sdk/billboard/features/#发布公告)，或者游戏正文添加了链接并且链接类型为「游戏内模块」的时候，可以通过监听自定义事件来获取消息，并做相应处理。
```

2022-08-03 04:33 UTC, fuchenshi commented on docs/sdk/billboard/guide.mdx
> +| 19999 | 其它错误，内容可以参考 description |
「其它错误」放在表格最后一行会不会比较好？

2022-08-03 04:33 UTC, fuchenshi commented on docs/sdk/billboard/guide.mdx
> +<Conditional region='cn'>详见文档关于[域名](/sdk/domain/guide/)的说明。</Conditional>
```suggestion
REST API 请求的 Base URL（下文 curl 示例中用 `{{host}}` 表示）即应用的 API <Conditional region='cn'>自定义</Conditional>域名，可以在控制台<Conditional region='cn'>绑定、</Conditional>查看。<Conditional region='cn'>详见文档关于[域名](/sdk/domain/guide/)的说明。</Conditional>
```

这里合为一行好了，不然会渲染成这样：

<img width="328" alt="截屏2022-08-03 12 26 27" src="https://user-images.githubusercontent.com/91254072/182524106-b7709a83-dc23-4e3d-b8cb-74cc979600b3.png">

2022-08-03 04:33 UTC, fuchenshi commented on docs/sdk/billboard/guide.mdx
> +| `id` | 公告id |
```suggestion
| `id` | 公告 id |
```

2022-08-03 04:33 UTC, fuchenshi commented on docs/sdk/billboard/guide.mdx
> +| `jump_location` | 跳转位置：content-正文、link-跳转链接、game |
缺少对 `game` 的描述。

2022-08-03 04:33 UTC, fuchenshi commented on docs/sdk/billboard/guide.mdx
> +| `id` | 公告id |
```suggestion
| `id` | 公告 id |
```

2022-08-03 04:33 UTC, fuchenshi commented on docs/sdk/billboard/guide.mdx
> +| `uuid` | 必须 | 设备唯一id字符串，示例："4e4105c7-781e-45c0-92ea-d595c75a3c2c" |
```suggestion
| `uuid` | 必须 | 设备唯一 id 字符串，示例："4e4105c7-781e-45c0-92ea-d595c75a3c2c" |
```

2022-08-03 04:33 UTC, fuchenshi commented on docs/sdk/billboard/guide.mdx
> +| `close_button_img` | 从导航接口中得到的关闭按钮url |
```suggestion
| `close_button_img` | 从导航接口中得到的关闭按钮 URL |
```

2022-08-03 05:32 UTC, fuchenshi approved these changes

2022-08-03 05:37 UTC, merged