增加公告最低支持的 TapSDK 版本，跳转游戏内模块补充说明
taptap/tds-docs pull request #231
Opened 2022-08-11 09:17 UTC by kylinbin

2022-08-11 09:18 UTC, kylinbin commented on docs/sdk/billboard/features.mdx
> +支持任意形式，例如字符串、ID、Url等，但填写的参数必须是唯一标识
```suggestion
支持任意形式，例如字符串、ID、URL 等，但填写的参数必须是唯一标识。
```

2022-08-11 10:29 UTC, fuchenshi requested changes

2022-08-11 10:29 UTC, fuchenshi commented on docs/sdk/billboard/features.mdx
> +- 支持版本：iOS / Andriod 最低支持版本 TapSDK 3.12.0，Unity 最低支持版本 TapSDK 3.12.1
```suggestion
- 支持版本：iOS / Android 最低支持版本 TapSDK 3.12.0，Unity 最低支持版本 TapSDK 3.12.1
```

2022-08-15 03:17 UTC, fuchenshi approved these changes

2022-08-15 03:18 UTC, merged