feat:update billboard interface
taptap/tds-docs pull request #293
Opened 2022-10-10 13:46 UTC by hexinghuaxd

2022-10-11 02:36 UTC, kylinbin approved these changes

2022-10-11 02:36 UTC, kylinbin commented on docs/sdk/billboard/guide.mdx
> +        // 公告已关闭, 如果有UI更新，请切换到Android主线程
```suggestion
        // 公告已关闭, 如果有 UI 更新，请切换到 Android 主线程
```

2022-10-11 02:59 UTC, kylinbin commented
- [ ] 等 SDK 发布之后再合并文档。

2022-10-14 09:52 UTC, fuchenshi requested changes

2022-10-14 09:52 UTC, fuchenshi commented on docs/sdk/billboard/guide.mdx
> +        // 公告已关闭, 如果有 UI 更新，请切换到 Android 主线程
```suggestion
        // 公告已关闭，如果有 UI 更新，请切换到 Android 主线程
```

2022-10-14 09:53 UTC, fuchenshi approved these changes

2022-10-17 13:54 UTC, merged