feat(tap-support): update the guide to align with the latest verison
taptap/tds-docs pull request #310
Opened 2022-10-28 08:10 UTC by leeyeh

2022-10-28 08:19 UTC, leeyeh commented on docs/tap-support.mdx
> +fields.Add("243", "iOS 15.1"); // 243 是在后台创建的「OS」字段的 ID
```suggestion
```

2022-10-31 08:11 UTC, onerain88 approved these changes

2022-10-31 08:11 UTC, onerain88 commented on docs/tap-support.mdx
> +TapSupport.Init("https://please-replace-with-your-customized.domain.com", "分类 ID", new TapSupportCallback
`分类 ID`，后面改成 productId 了吧？

2022-10-31 08:19 UTC, kelv1nq1an requested changes
rootCategoryID 更改为 productID，以及 open 接口修改

2022-10-31 08:19 UTC, kelv1nq1an commented on docs/tap-support.mdx
> +[TapSupport openSupportView:@"/path"];
```suggestion
[TapSupport openSupportViewWithPath:@"/path" metaData:nil fieldsData:nil];
```

2022-10-31 08:19 UTC, kelv1nq1an commented on docs/tap-support.mdx
> +[TapSupport openSupportView:@"/" fieldsData:fields];
```suggestion
[TapSupport openSupportViewWithPath:@"/" metaData:nil fieldsData:fields];
```

2022-10-31 08:19 UTC, kelv1nq1an commented on docs/tap-support.mdx
> +config.rootCategoryID = @"分类 ID";
```suggestion
config.productID = @"分类 ID";
```

2022-10-31 08:20 UTC, lc1006 commented on docs/tap-support.mdx
> +TapSupportConfig config = new TapSupportConfig("https://please-replace-with-your-customized.domain.com", "分类 ID")
android 这里还是需要 TapSupportCallback 的

2022-10-31 08:22 UTC, leeyeh commented on docs/tap-support.mdx
> +TapSupportConfig config = new TapSupportConfig("https://please-replace-with-your-customized.domain.com", "分类 ID")
就算不关心小红点也需要 callback 是吧。那我加回来。

2022-10-31 08:23 UTC, lc1006 commented on docs/tap-support.mdx
> +```
android  openSupportView(String path, Map<String, Object> metaData, Map<String, Object> fieldsData) 参数个数不对

2022-10-31 08:53 UTC, kelv1nq1an approved these changes

2022-10-31 13:16 UTC, leeyeh commented on docs/tap-support.mdx
> +在初始化 SDK 之前，有一些准备工作需要完成：
这里的准备其实严格上不是「需要提前完成的一次性工作」，更多的是在解释「初始化时需要的参数要去哪里找」，可以看做是「初始化」说明的一部分。

2022-11-01 03:27 UTC, merged