chore: add restrictions on _User fields
taptap/tds-docs pull request #335
Opened 2022-11-25 07:02 UTC by kylinbin

https://xindong.slack.com/archives/C01S9A1B4GK/p1669275699910999

2022-11-25 07:03 UTC, kylinbin commented on docs/sdk/authentication/guide.mdx
> +开发者可以使用内建账户系统设置更多用户信息，比如通过设置 `nickname` 字段来添加昵称：
限制了字段，生日相关描述去掉了。

2022-11-25 07:05 UTC, kylinbin commented on docs/sdk/authentication/guide.mdx
这里「用户的查询」代码全部去掉了。只留下了文字说明有哪些限制、建议怎么使用之类。

2022-11-25 07:18 UTC, fuchenshi requested changes

2022-11-25 07:18 UTC, fuchenshi commented on docs/sdk/authentication/guide.mdx
> +一些开发者可能希望将所有用户相关的信息都一股脑地存在内建账户系统，比如游戏可能将用户的等级、拥有的装备等信息都存在内建账户里，但我们并不推荐也不支持这么做。
如果读者手里的应用是个「新应用」，那么后面这段是不是并不适用（因为本来也不存在往用户表里写其他字段的可能）？或许可以考虑折叠一下。

2022-11-25 07:18 UTC, fuchenshi commented on i18n/en/docusaurus-plugin-content-docs/current/sdk/authentication/guide.mdx
> +The account system supports only two extra fields besides the built-in ones: `nickname` and `avatar`, adding other new fields will cause an error.
```suggestion
The account system supports only two extra fields besides the built-in ones: `nickname` and `avatar`. Adding other new fields will cause an error.
```

2022-11-25 07:25 UTC, kylinbin commented on docs/sdk/authentication/guide.mdx
> +一些开发者可能希望将所有用户相关的信息都一股脑地存在内建账户系统，比如游戏可能将用户的等级、拥有的装备等信息都存在内建账户里，但我们并不推荐也不支持这么做。
对，这里一段主要是想解释「为什么」这么做 🤔

2022-11-25 07:55 UTC, nicecui commented on docs/sdk/authentication/guide.mdx
> +开发者可以使用内建账户系统设置更多用户信息，比如通过设置 `nickname` 字段来添加昵称：
建议：开发者可以使用内建账户系统设置 `nickname` 和 `avatar`。

因为确实只剩这两个了...

2022-11-25 07:55 UTC, nicecui commented on docs/sdk/authentication/guide.mdx
> +新应用的内建账户系统目前只支持内置字段和两个自定义字段： `nickname`（昵称） 以及 `avatar`（头像），添加其他新的字段会报错。
感觉这段话可以挪上去，也不用强调「新应用」，因为「新应用」的定义不清楚...所有新看到这篇文档的用户默认都是新应用

2022-11-25 07:55 UTC, nicecui commented on docs/sdk/authentication/guide.mdx
> +一些开发者可能希望将所有用户相关的信息都一股脑地存在内建账户系统，比如游戏可能将用户的等级、拥有的装备等信息都存在内建账户里，但我们并不推荐也不支持这么做。
呃，新应用以后也没机会这么做了...要不要直接说，让开发者存到其他的表里面，并关联  _User 表，直接写一个最佳实践的方案...

2022-11-28 03:51 UTC, fuchenshi requested changes

2022-11-28 03:51 UTC, fuchenshi commented on i18n/en/docusaurus-plugin-content-docs/current/sdk/authentication/guide.mdx
>  currentUser.put("nickname");
```suggestion
currentUser.put("nickname", "Tarara");
```

2022-11-28 03:51 UTC, fuchenshi commented on i18n/en/docusaurus-plugin-content-docs/current/sdk/authentication/guide.mdx
> +Therefore, we restrict the use of fields. It’s totally fine to store a small amount of data that’s only accessible to its owners in the user account,
Nope, it's not fine.

2022-11-28 05:43 UTC, fuchenshi approved these changes

2022-11-28 06:02 UTC, merged