fix(multiplayer): client init parameters
taptap/tds-docs pull request #348
Opened 2022-12-06 09:30 UTC by kylinbin

https://dc.leanticket.cn/tickets/12430

2022-12-06 09:53 UTC, fuchenshi requested changes

2022-12-06 09:53 UTC, fuchenshi commented on docs/sdk/multiplayer/features.mdx
> +</Conditional>
LeanCloud 和 TDS 的内容相同，可以不用 `Conditional`。

2022-12-06 09:53 UTC, fuchenshi commented on docs/sdk/multiplayer/guide/cs.mdx
> +    playServer: "https://your_server_url" // 游戏的 API 域名
这里少了 `gameVersion`。

2022-12-06 10:01 UTC, kylinbin commented on docs/sdk/multiplayer/features.mdx
> +</Conditional>
这个地方上来就 Play，也没有初始化什么比较奇怪，正想留着问问 @onerain88 要不要改改，JS 的示例看起来更清楚一点

2022-12-07 03:18 UTC, kylinbin commented on docs/sdk/multiplayer/features.mdx
> +</Conditional>
暂时不想动这里，所以先去掉 `Conditional` 和对应内容了。

2022-12-07 03:27 UTC, fuchenshi approved these changes

2022-12-07 03:37 UTC, merged