feat(storage): best practice
taptap/tds-docs pull request #383
Opened 2023-01-16 06:36 UTC by kylinbin

TDS + LC 文档：

- 新增 点号使用指南 和 数据模型设计 两篇。

2023-01-16 07:12 UTC, fuchenshi requested changes

2023-01-16 07:12 UTC, fuchenshi commented on docs/sdk/storage/best-practice/dot-notation.md
> +也就是说，在上面的例子中，`member` 对象上必须已经存在 `occupation` 字段，否则直接使用 `occupation.profession` 会报错。
刚刚测试了一下：

新建对象时，使用点号设置属性（`occupation.profession`）总是会遇到报错，即使先将字段（`occupation`）的值设为 `{}`。报错内容为：

```
Invalid key name. Keys are case-sensitive and 'a-zA-Z0-9_' are the only valid characters.Invalid BSON field name occupation.profession
```

更新对象时，无论是否存在字段（`occupation`），使用点号设置属性（`occupation.profession`）都不会遇到报错。

2023-01-16 07:12 UTC, fuchenshi commented on docs/sdk/storage/best-practice/dot-notation.md
> +member.set("occupation": "{}")
这里的 JS 代码存在语法错误，不过并不影响前面提到的问题。

```suggestion
member.set("occupation", { "profession": "Software Developer" })

// 下面这样也行，但是不如上一种方式简洁，因此不推荐使用。
member.set("occupation", {})
```

2023-01-17 03:11 UTC, kylinbin commented on docs/sdk/storage/best-practice/dot-notation.md
> +也就是说，在上面的例子中，`member` 对象上必须已经存在 `occupation` 字段，否则直接使用 `occupation.profession` 会报错。
试了一下，确实有这个问题。。

2023-01-17 03:17 UTC, fuchenshi approved these changes

2023-01-17 03:27 UTC, merged