feat(auth): add billboard 2.0 design guide
taptap/tds-docs pull request #409
Opened 2023-02-15 08:05 UTC by SXiaoXu

**设计稿见**[这里](https://www.figma.com/file/KsOZ492eB5qgOgyOx42bot/SDK%E5%AF%B9%E5%A4%96%E8%AE%BE%E8%AE%A1%E8%A7%84%E8%8C%83%E3%80%90%E8%AE%BE%E8%AE%A1%E3%80%91?node-id=2539%3A11476&t=RUgtp4sIy9WWf2E8-0)，**更新内容：**
* 新增「开屏公告」和「跑马灯公告」模块
* 公告类型展示图替换
* 全部标题名称改xx公告，而非之前的xx模版
* 导航公告需替换两张切图

2023-02-15 09:04 UTC, fuchenshi requested changes

2023-02-15 09:04 UTC, fuchenshi commented on docs/design/design-billboard.mdx
> +    caption="B.图片公告"
```suggestion
    caption="D.图片公告"
```

2023-02-15 09:06 UTC, SXiaoXu commented
先不合并，设计的同学还在 review 中。

2023-02-15 09:06 UTC, fuchenshi approved these changes

2023-02-16 03:54 UTC, fuchenshi requested changes

2023-02-16 03:54 UTC, fuchenshi commented on docs/design/design-billboard.mdx
> +    caption="B.图片公告"
这里又改回来了…😂

2023-02-16 05:03 UTC, SXiaoXu commented on docs/design/design-billboard.mdx
> +    caption="B.图片公告"
我的错，已改

2023-02-16 05:08 UTC, fuchenshi approved these changes

2023-02-16 05:31 UTC, merged