Contributing guide markdown
taptap/tds-docs pull request #43
Opened 2022-02-22 12:34 UTC by weakish

2022-03-14 12:45 UTC, kylinbin approved these changes
读了一遍。非常详细了，看不出有什么要改的 🎉

2022-03-15 02:25 UTC, fuchenshi requested changes

2022-03-15 02:25 UTC, fuchenshi commented on CONTRIBUTING.md
> +如果找不到相应文件，**需要点击 `Enable indexing` 启用索引。**
https://code.visualstudio.com/updates/v1_65#_vs-code-for-the-web

最近发布的 VS Code 1.65 对搜索功能的行为作了一些改动：

> Workspace search and Find All References will now download and index a full copy of the repository by default, rather than defaulting to providing partial results as before.

需要关注一下这里的指引内容是否需要调整。

2022-03-15 02:25 UTC, fuchenshi commented on CONTRIBUTING.md
> +相应地，`/docs/sdk/achievement_category_.json` 的内容为：
```suggestion
相应地，`/docs/sdk/achievement/_category_.json` 的内容为：

```

2022-03-15 03:52 UTC, weakish commented on CONTRIBUTING.md
> +如果找不到相应文件，**需要点击 `Enable indexing` 启用索引。**
试了下，果然现在 github.dev 会自动建立索引了。另外因为是换了个浏览器测试，发现其实第一次使用 github.dev 还需要授权，把相应内容也补充上了。

2022-03-15 03:59 UTC, fuchenshi requested changes

2022-03-15 03:59 UTC, fuchenshi commented on CONTRIBUTING.md
> +自己 fork 上的内容可能不是最新的，比如下面的截图中 GitHub 显示：
截图没加进来。

2022-03-15 04:07 UTC, weakish commented on CONTRIBUTING.md
> +自己 fork 上的内容可能不是最新的，比如下面的截图中 GitHub 显示：
补上了

2022-03-15 04:08 UTC, fuchenshi approved these changes

2022-03-15 05:09 UTC, merged