UE achievement
taptap/tds-docs pull request #442
Opened 2023-03-17 06:52 UTC by Xvpang

添加成就UE4部分

2023-03-17 07:07 UTC, kylinbin requested changes

2023-03-17 07:07 UTC, kylinbin commented on docs/sdk/achievement/guide.mdx
> +{`
看预览这里多出一个空行来。下一行内容直接放在 ` 后面就好。

2023-03-17 07:07 UTC, kylinbin commented on docs/sdk/achievement/guide.mdx
> +  // 添加项目依赖的其它模块
```suggestion
  // 添加 TapTap 成就系统
```

改成这样更明确？也和其他 SDK 依赖添加模块一致一些。

2023-03-17 07:07 UTC, kylinbin commented on docs/sdk/achievement/guide.mdx
> +Unity和UE4的SDK在需要设置项目的名称和图标，用于在成就详情页面显示
```suggestion

Unity 和 UE4 的 SDK 需要设置项目的名称和图标，用于在成就详情页面。
```

「成就详情页面」具体指哪个页面，是否有有对应产品文档的链接（如果没有，需要在这里解释清楚，或者在产品文档加内容）。

2023-03-17 07:07 UTC, kylinbin commented on docs/sdk/achievement/guide.mdx
> +
多了空行

2023-03-17 07:07 UTC, kylinbin commented on docs/sdk/achievement/guide.mdx
> +
多了两行空行

2023-03-17 07:22 UTC, WatchMan-Wang commented on docs/sdk/achievement/guide.mdx
> +  // 添加项目依赖的其它模块
赞同

2023-03-17 07:34 UTC, WatchMan-Wang commented on docs/sdk/achievement/guide.mdx
> +Unity和UE4的SDK在需要设置项目的名称和图标，用于在成就详情页面显示
觉得去掉后面的「用于在成就详情页面」比较好，项目名称和图标属于成就的基础信息，文档功能介绍已有相关说明，而且在 DC 后台创建成就也需要按步骤填写项目名称和图标的。感觉问题不大。

2023-03-17 07:39 UTC, WatchMan-Wang approved these changes

2023-03-17 07:49 UTC, kylinbin commented on docs/sdk/achievement/guide.mdx
> +Unity和UE4的SDK在需要设置项目的名称和图标，用于在成就详情页面显示
去掉没法解释这些代码用来干什么。「文档功能介绍已有相关说明」，有的话上链接啊 🤔

2023-03-17 08:45 UTC, WatchMan-Wang commented on docs/sdk/achievement/guide.mdx
> +//@TODO Unity 设置项目图标和名字
这里的 Unity 代码是新加入的吗？之前一直并没有说明，而且也有一些开发者正常接入了。

2023-03-20 04:13 UTC, Xvpang commented on docs/sdk/achievement/guide.mdx
> +Unity和UE4的SDK在需要设置项目的名称和图标，用于在成就详情页面显示
已经添加详情页面配图，修改“项目”为“应用”（感觉更准确）

2023-03-20 04:15 UTC, Xvpang commented on docs/sdk/achievement/guide.mdx
> +//@TODO Unity 设置项目图标和名字
这个接口是适配PC需要添加的，之前没有
TODO已经删除，之前是给Unity预留的位置

2023-03-20 04:18 UTC, Xvpang commented
新添加详情页面配图，删除Unity TODO

2023-03-20 10:10 UTC, SXiaoXu commented on docs/sdk/achievement/guide.mdx
> +Unity 和 UE4 的 SDK 在需要设置应用的名称和图标，用于在成就详情页面显示。
```suggestion
Unity 和 UE4 的 SDK 需要设置应用的名称和图标，用于在成就详情页面显示。
```

2023-03-20 10:10 UTC, SXiaoXu commented on docs/sdk/achievement/guide.mdx
> +（图中：左上角图片为应用图标，“人类跌落梦境”为应用名称）
```suggestion
（图中：左上角图片为应用图标，「人类跌落梦境」为应用名称）
```

2023-03-20 11:43 UTC, WatchMan-Wang commented on docs/sdk/achievement/guide.mdx
>  成就 SDK 中包含多个监听回调，分别会在初始化数据成功、初始化数据失败以及成就进度更新时被调用，请特别注意初始化数据成功的回调，这是成就 SDK 正常使用的前提，初始化数据失败时请提示用户或者在合适的时候重新初始化数据。
「初始化数据失败时请提示用户或者在合适的时候重新初始化数据」 @SXiaoXu 我理解初始化失败字面意思有两个建议是给开发者建议的：1、直接给出提示，可能用户体验友好点。2、在其他合适的地方重新初始化。
而你给出的建议好像是让玩家更改业务逻辑。这里的用户代指玩家。

2023-03-21 02:33 UTC, SXiaoXu approved these changes

2023-03-21 02:44 UTC, kylinbin approved these changes

2023-03-21 02:47 UTC, kylinbin commented on docs/sdk/achievement/guide.mdx
> +## 模块基础设置
前面有一条 comment 提到「这个接口是适配PC需要添加的」

所以设置这些也是适用于 PC 对吧，非 PC 游戏不用加这些对吧？那在文档里要注明一下

2023-03-21 02:49 UTC, kylinbin commented on docs/sdk/achievement/guide.mdx
> +## 模块基础设置
另外给 Unity 留的 TODO 删掉了是 Unity 不需要配置吗
- 不需要的话，下面这段「Unity 和 UE4 的 SDK 需要设置应用的名称和图标，用于在成就详情页面显示。」要改
- 需要的话，unity 这部分谁可以补一下呢，不然这个 pr 不完整

2023-03-21 04:09 UTC, Xvpang commented
合并了Unity和UE4部分，把文字描述也分离开，并且放在最上面，这个应该算基础设置，Unity是只有PC需要设置，UE4全部平台都需要设置

2023-03-21 04:23 UTC, Xvpang commented on docs/sdk/achievement/guide.mdx
> +## 模块基础设置
合并了Unity和UE4部分，把文字描述也分离开，并且放在最上面，这个应该算基础设置，Unity是只有PC需要设置，UE4全部平台都需要设置
合并的时候确认一下，Unity的是否正确，可能会上下两个地方都有

2023-03-21 05:17 UTC, merged