demo: engine dotnet redis, mysql, mongo
taptap/tds-docs pull request #543
Opened 2023-06-15 08:38 UTC by onerain88

2023-06-15 08:43 UTC, jysperm approved these changes

2023-06-15 08:51 UTC, fuchenshi requested changes

2023-06-15 08:51 UTC, fuchenshi commented on docs/sdk/engine/database/redis.mdx
> +<TabItem value='dotnet'>
这个 `<TabItem></TabItem>` 是不是需要移除？

2023-06-15 08:55 UTC, jysperm commented on docs/sdk/engine/database/redis.mdx
> +<TabItem value='dotnet'>
这一整段好像都和下面是重复的（可以点 View file 查看这整个文件）

2023-06-15 08:56 UTC, fuchenshi commented on docs/sdk/engine/database/redis.mdx
> +<TabItem value='dotnet'>
对，我指的就是从这个 `<TabItem value='dotnet'>` 到后面的 `</TabItem>` 这部分是不是不需要了。

2023-06-16 06:14 UTC, fuchenshi approved these changes

2023-06-16 06:14 UTC, merged