Dev vulcan
taptap/tds-docs pull request #562
Opened 2023-06-20 05:58 UTC by caosir520

2023-06-20 06:39 UTC, caosir520 commented
重拉一个提交

2023-06-27 09:56 UTC, fuchenshi requested changes

2023-06-27 09:56 UTC, fuchenshi commented on .ci/leancloud/zh-Hans/sdk/start/guide.mdx
> +LeanCloud 是 领先的 Serverless 云服务为产品开发提供强有力的后端支持，旨在帮助开发者降低研发、运营维护等阶段投入的精力和成本。
```suggestion
LeanCloud 是领先的 Serverless 云服务，为产品开发提供强有力的后端支持，旨在帮助开发者降低研发、运营维护等阶段投入的精力和成本。
```

注意格式和语法。

2023-06-27 09:56 UTC, fuchenshi commented on .ci/leancloud/zh-Hans/sdk/start/guide.mdx
> +[内建账户](/sdk/authentication/guide/) ： 帮助开发者快速低成本地构建一个安全可靠的用户登录系统，支持用户采用包括邮箱，手机号在内的多种账号来登录你的应用。
```suggestion
[内建账户](/sdk/authentication/guide/) ： 帮助开发者快速低成本地构建一个安全可靠的用户登录系统，支持用户采用包括邮箱、手机号在内的多种账号来登录你的应用。
```

2023-06-27 09:56 UTC, fuchenshi commented on .ci/leancloud/zh-Hans/sdk/start/guide.mdx
> +[短信](/sdk/sms/guide/) ： 验证码短信 · 系统通知 · 活动通知，99% 到达率，稳定可靠。用户注册、登录，重要操作的用户身份验证，营销活动通知，等等。凡是需要强身份验证的地方，手机短信都可派上用场。
```suggestion
[短信](/sdk/sms/guide/) ： 支持发送验证码短信、系统通知、活动通知等各类短信，提供 99% 的到达率，稳定可靠。支持用户注册、登录、执行重要操作时的身份验证。凡是需要强身份验证的地方，手机短信都可派上用场。
```

2023-06-27 09:56 UTC, fuchenshi commented on .ci/leancloud/zh-Hans/sdk/start/guide.mdx
> +[多人在线对战功能](/sdk/multiplayer/features/) ： 多人在线对战是 LeanCloud 专门针对多人在线类型的游戏推出的后端服务。开发者不需要自己搭建后端系统，利用云服务就可以轻松实现游戏内玩家匹配、在线对战消息同步等功能。
```suggestion
[多人在线对战](/sdk/multiplayer/features/) ： 多人在线对战是 LeanCloud 专门针对多人在线类型的游戏推出的后端服务。开发者不需要自己搭建后端系统，利用云服务就可以轻松实现游戏内玩家匹配、在线对战消息同步等功能。
```

2023-06-27 09:56 UTC, fuchenshi commented on docs/sdk/authentication/faq.mdx
> +### 内建账户用户名和 TAPTAP 账户用户名不一致
```suggestion
### 内建账户用户名和 TapTap 账户用户名不一致
```

2023-06-27 09:56 UTC, fuchenshi commented on docs/sdk/authentication/faq.mdx
> +目前由于 TapTap 昵称和游戏昵称是分开的两个部分，我们的设计逻辑是，第一次使用 TapTap 登录后会将登录的信息存到内建账户中，但是后续如果修改 TapTap 的昵称，内建账户中的原先的存的 昵称是不会更新的，如果想要使用更新后的昵称，
```suggestion
目前由于 TapTap 昵称和游戏昵称是分开的两个部分，我们的设计逻辑是，第一次使用 TapTap 登录后会将登录的信息存到内建账户中，但是后续如果修改 TapTap 的昵称，内建账户中原先保存的昵称是不会更新的。如果想要使用更新后的昵称，
```

2023-06-27 09:56 UTC, fuchenshi commented on docs/sdk/authentication/faq.mdx
> +可以尝试游戏内新增一个[修改昵称](/sdk/authentication/guide/#设置其他用户属性)的逻辑，用户输入昵称，然后客户端调用内建账户的 设置其他用户属性的方法，就可以更新昵称了
```suggestion
可以尝试游戏内新增一个[修改昵称](/sdk/authentication/guide/#设置其他用户属性)的逻辑，用户输入昵称，然后客户端调用内建账户的「设置其他用户属性」的方法，就可以更新昵称了。
```

2023-06-27 09:56 UTC, fuchenshi commented on docs/sdk/authentication/faq.mdx
> +如果在 `开发者中心 > 你的游戏 > 游戏服务 > 云服务 > 内建账户 > 设置` 中勾选了 密码修改后，强制客户端重新登录，那么当一个用户修改密码后，该用户的 session token 会被重置。此时需要让用户重新登录，否则会遇到 403 (Forbidden) 错误
```suggestion
如果在 `开发者中心 > 你的游戏 > 游戏服务 > 云服务 > 内建账户 > 设置` 中勾选了「密码修改后，强制客户端重新登录」，那么当一个用户修改密码后，该用户的 session token 会被重置。此时需要让用户重新登录，否则会遇到 403 (Forbidden) 错误。
```

2023-06-27 09:56 UTC, fuchenshi commented on docs/sdk/start/faq.mdx
> +目前 TapTap 这边的要求是同一个身份证号最多只能实名 5 个TapTap 账号，对于游戏账号实名没有限制。
```suggestion
目前 TapTap 的要求是同一个身份证号最多只能实名 5 个 TapTap 账号，对于游戏账号实名没有限制。
```

2023-06-27 09:56 UTC, fuchenshi commented on docs/sdk/start/faq.mdx
> +- 2、检查项目初始化代码中 Client id、ClientToken、ServerUrl （需要以 https:// 开头）是否和开发者后台保持一致，
```suggestion
1. 检查开发者后台应用配置中是否开通了 TapTap 登录服务；
2. 检查项目初始化代码中 ClientId、ClientToken、ServerUrl （需要以 `https://` 开头）是否和开发者后台保持一致。
```

2023-06-27 09:56 UTC, fuchenshi commented on docs/sdk/start/faq.mdx
> +按照国家新闻出版署[《关于进一步严格管理切实防止未成年人沉迷网络游戏的通知》](https://www.nppa.gov.cn/xxfb/tzgs/202108/t20210830_666285.html)，各游戏出版运营企业均须在游戏内落实游戏实名认证和防沉迷新策略,
```suggestion
按照国家新闻出版署[《关于进一步严格管理切实防止未成年人沉迷网络游戏的通知》](https://www.nppa.gov.cn/xxfb/tzgs/202108/t20210830_666285.html)，各游戏出版运营企业均须在游戏内落实游戏实名认证和防沉迷新策略。
```

2023-06-27 09:56 UTC, fuchenshi commented on docs/sdk/start/faq.mdx
> +如果没有版号的游戏可以接入 TDS 推出的[实名认证防沉迷](/sdk/anti-addiction/features/)
```suggestion
对于没有版号的游戏，可以接入 TDS 推出的[实名认证防沉迷](/sdk/anti-addiction/features/)。
```

2023-06-27 09:56 UTC, fuchenshi commented on docs/sdk/start/faq.mdx
> +自 3.7.1 版本开始，快速认证不依赖 TapTap 登录 SDK 故防沉迷和登录**没有**强关联关系，但是使用了 TAPTAP 登录后可以使用防沉迷的[快速认证](/sdk/anti-addiction/features/#taptap-快速认证)在经过玩家同意授权之后，允许玩家使用在 TapTap 里已经通过国家认证的实名信息快速完成游戏中的认证流程。
```suggestion
自 3.7.1 版本开始，快速认证不依赖 TapTap 登录 SDK，故防沉迷和登录**没有**强关联关系。但是使用了 TapTap 登录后，可以使用防沉迷的[快速认证](/sdk/anti-addiction/features/#taptap-快速认证)，在经过玩家同意授权之后，允许玩家使用在 TapTap 里已经通过国家认证的实名信息快速完成游戏中的认证流程。
```

2023-06-27 09:56 UTC, fuchenshi commented on docs/sdk/start/faq.mdx
> +**否则**可以使用直接使用我们提供的[实名认证](/sdk/anti-addiction/features/#游戏实名认证与防沉迷)，TDS 已为开发者自动对接了中宣部网络游戏防沉迷实名认证系统，并以开发者主体进行信息上报，符合中宣部对游戏企业接入的合规要求。
```suggestion
除此之外，还可以使用直接使用我们提供的[实名认证](/sdk/anti-addiction/features/#游戏实名认证与防沉迷)功能。TDS 已为开发者自动对接了中宣部网络游戏防沉迷实名认证系统，并以开发者主体进行信息上报，符合中宣部对游戏企业接入的合规要求。
```

2023-06-27 09:56 UTC, fuchenshi commented on docs/sdk/start/faq.mdx
> +### 防沉迷后退出账号后，再次启动游戏时候，还是直接登录上去了。
```suggestion
### 实名认证通过后退出账号，再次启动游戏，会跳过实名认证流程
```

2023-06-27 09:56 UTC, fuchenshi commented on docs/sdk/start/faq.mdx
> +自 3.7.1 版本开始，快速认证不依赖 TapTap 登录 SDK 故防沉迷和登录**没有**强关联关系，所以 换账号之前需要退出当前账号。而第一次认证会触发实名认证弹窗，让玩家授权游戏获取 TapTap 实名信息或输入身份信息，认证通过后，后面每一次以同样的 `userIdentifier` （唯一标识）调用认证接口都会直接拿到第一次认证的结果，不再触发弹窗。
```suggestion
自 3.7.1 版本开始，快速认证不依赖 TapTap 登录 SDK，故防沉迷和登录**没有**强关联关系。玩家首次进入游戏会触发实名认证弹窗，让玩家授权游戏获取 TapTap 实名信息或输入身份信息，认证通过后，后面每一次以同样的 `userIdentifier` （唯一标识）调用认证接口都会直接拿到第一次认证的结果，不再触发弹窗。如玩家需要换用其他账号登录，需要主动退出账号。
```

2023-06-27 09:56 UTC, fuchenshi commented on docs/sdk/tapdb/faq/tran.mdx
> +A：请先检查代码中是否设置了 [user_id](/sdk/tapdb/sdk/client-side-integration/#设置账号-id) ，如果不确认的话可以去后台使用 SQL 查询中可以看到曾经上报过的 user_id
```suggestion
A：请先检查代码中是否设置了 [user_id](/sdk/tapdb/sdk/client-side-integration/#设置账号-id) 。如果不确定的话可以去后台使用 SQL 查询，在结果中可以看到曾经上报过的 user_id。
```

2023-06-27 09:56 UTC, fuchenshi commented on docs/sdk/tapdb/faq/tran.mdx
> +检查上报的 user_id 里有没有需要上报的用户的 user_id .
```suggestion
检查上报的 user_id 里有没有需要上报的用户的 user_id。
```

2023-06-27 09:56 UTC, fuchenshi commented on docs/sdk/tds-gift/faq.mdx
> +请检查您的请求中 header 信息，是否有带上特殊的 User Agent。
```suggestion
请检查您请求的 header 是否有带上特殊的 User Agent。
```

2023-06-27 09:56 UTC, fuchenshi commented on docs/sdk/tds-gift/faq.mdx
> +二次校验是您按照规范开发校验接口并将地址配置后台中，由兑换系统去请求。
```suggestion
使用二次校验需要您按照规范开发校验接口并将地址配置到后台中，由兑换系统发起请求。
```

2023-06-27 09:56 UTC, fuchenshi commented on docs/sdk/tds-gift/faq.mdx
> +可以参考文档中[签名部分](/sdk/tds-gift/guide/#签名)。
```suggestion
可以参考文档的[签名部分](/sdk/tds-gift/guide/#签名)。
```

2023-06-27 09:56 UTC, fuchenshi commented on docs/sdk/tds-gift/faq.mdx
> +可以通过开发者后台 -> 礼包服务中检查活动开关是否打开，以及礼包码是否失效；
```suggestion
可以通过 **开发者后台 -> 礼包服务** 检查活动开关是否打开，以及礼包码是否失效。
```

2023-06-27 09:56 UTC, fuchenshi commented on docs/sdk/tds-gift/faq.mdx
> +当前最大版本礼包时间为 2038-01-19 11:14:07
```suggestion
当前最大礼包时间为 2038-01-19 11:14:07。
```

2023-06-27 09:56 UTC, fuchenshi commented on i18n/en/docusaurus-plugin-content-docs/current/sdk/authentication/faq.mdx
> +sidebar_label:  Asked Questions
```suggestion
title:  FAQ
sidebar_label:  FAQ
```

2023-06-27 09:56 UTC, fuchenshi commented on i18n/en/docusaurus-plugin-content-docs/current/sdk/authentication/faq.mdx
> +### Built-in account username is inconsistent with TAPTAP account username
```suggestion
### The built-in account username is inconsistent with the TapTap account username
```

2023-06-27 09:56 UTC, fuchenshi commented on i18n/en/docusaurus-plugin-content-docs/current/sdk/authentication/faq.mdx
> +Currently, TapTap nicknames and game nicknames are separate. Our design logic is that after using TapTap login for the first time, the login information will be stored in the built-in account. Howeve
```suggestion
Currently, TapTap nicknames and game nicknames are separate. Our design logic is that after using TapTap login for the first time, the login information will be stored in the built-in account. However, if you modify your TapTap nickname later, the original nickname stored in the built-in account will not be updated. If you want to use the updated nickname, you can try adding a [change nickname](/sdk/authentication/guide/#setting-other-user-properties) feature in the game. After a user provides their new nickname, the client calls the SDK method for setting other user attributes to update the nickname.
```

2023-06-27 09:56 UTC, fuchenshi commented on i18n/en/docusaurus-plugin-content-docs/current/sdk/authentication/faq.mdx
> +If you have checked "Force client to re-login after password change" in Developer Center > Your Game > Game Services > Cloud Services > Built-in Accounts > Settings, then when a user changes their pa
```suggestion
If you have checked "Force client to re-login after password change" in Developer Center > Your Game > Game Services > Cloud Services > Built-in Accounts > Settings, then when a user changes their password, their session token will be reset. At this point, you need to prompt the user to log in again; otherwise, they will encounter a 403 (Forbidden) error.
```

2023-06-27 09:56 UTC, fuchenshi commented on i18n/en/docusaurus-plugin-content-docs/current/sdk/start/faq.mdx
> +### Is there a limit to the number of accounts with real-name authentication for the same ID card?
```suggestion
### Is there a limit to the number of accounts with real-name authentication for the same ID?
```

2023-06-27 09:56 UTC, fuchenshi commented on i18n/en/docusaurus-plugin-content-docs/current/sdk/start/faq.mdx
> +Currently, TapTap requires that a single ID card can only be used for real-name authentication on up to 5 TapTap accounts. There is no limit on real-name authentication for game accounts.
```suggestion
Currently, TapTap requires that a single ID can only be used for real-name authentication on up to 5 TapTap accounts. There is no limit on real-name authentication for game accounts.
```

2023-06-27 09:56 UTC, fuchenshi commented on i18n/en/docusaurus-plugin-content-docs/current/sdk/start/faq.mdx
> +### Login prompt: this app is not allowed for this domain
```suggestion
### The player sees this message when trying to log in: this app is not allowed for this domain
```

2023-06-27 09:56 UTC, fuchenshi commented on i18n/en/docusaurus-plugin-content-docs/current/sdk/start/faq.mdx
> +- 2. Ensure that the Client id, ClientToken, and ServerUrl (must start with https://) in the project initialization code are consistent with those in the developer console.
```suggestion
1. Check whether the TapTap login service is enabled in the application configuration in the developer console;
2. Ensure that the ClientId, ClientToken, and ServerUrl (must start with `https://`) in the project initialization code are consistent with those in the developer console.
```

2023-06-27 09:56 UTC, fuchenshi commented on i18n/en/docusaurus-plugin-content-docs/current/sdk/start/faq.mdx
> +### Do individual/group developers need to implement anti-addiction measures?
```suggestion
### Is it required for developers (including organizations) to implement anti-addiction measures?
```

2023-06-27 09:56 UTC, fuchenshi commented on i18n/en/docusaurus-plugin-content-docs/current/sdk/start/faq.mdx
> +According to the Notice of Further Strict Management and Effective Prevention of Minors' Addiction to Online Games issued by China's National Press and Publication Administration [link](https://www.n
```suggestion
According to the Notice of Further Strict Management and Effective Prevention of Minors' Addiction to Online Games issued by China's National Press and Publication Administration [link](https://www.nppa.gov.cn/xxfb/tzgs/202108/t20210830_666285.html), all game publishing and operating companies must implement real-name authentication and anti-addiction policies within their games. Games without a license can use TDS's [Real-name Authentication and Anti-addiction](/sdk/anti-addiction/features/) system.
```

2023-06-27 09:56 UTC, fuchenshi commented on i18n/en/docusaurus-plugin-content-docs/current/sdk/start/faq.mdx
> +Starting from version 3.7.1, quick authentication does not rely on TapTap Login SDK, so there is **no** strong association between anti-addiction and login. However, after using TAPTAP login, you can
```suggestion
Starting from version 3.7.1, Quick Verification does not rely on the TapTap Login SDK, so there is **no** strong association between anti-addiction and login. However, after using TapTap login, you can use [Quick Verification](/sdk/anti-addiction/features/#taptap-quick-verification) for anti-addiction. With the player's consent, they can quickly complete the in-game authentication process using their real-name information verified by TapTap.
```

2023-06-27 09:56 UTC, fuchenshi commented on i18n/en/docusaurus-plugin-content-docs/current/sdk/start/faq.mdx
> +**Otherwise**, you can use our provided [Real-name Authentication](/sdk/anti-addiction/features/#real-name-verification-and-anti-addiction). TDS has automatically connected to the Ministry of Publici
```suggestion
**Otherwise**, you can use our provided [Real-name Authentication](/sdk/anti-addiction/features/#real-name-verification-and-anti-addiction). TDS has connected to the Ministry of Publicity's online game anti-addiction and real-name authentication system and reports information under the developer's name, meeting regulatory requirements.
```

2023-06-27 09:56 UTC, fuchenshi commented on i18n/en/docusaurus-plugin-content-docs/current/sdk/start/faq.mdx
> +### After exiting an account due to anti-addiction, the game is logged in directly when restarted.
```suggestion
### After logging out an account that has completed the real-name verification and restarting the game, the real-name verification process is skipped.
```

2023-06-27 09:56 UTC, fuchenshi commented on i18n/en/docusaurus-plugin-content-docs/current/sdk/start/faq.mdx
> +Starting from version 3.7.1, quick authentication does not rely on TapTap Login SDK, so there is **no** strong association between anti-addiction and login. Therefore, you need to log out of the curr
```suggestion
Starting from version 3.7.1, quick authentication does not rely on TapTap Login SDK, so there is **no** strong association between anti-addiction and login. Therefore, you need to log out of the current account before switching accounts. When a player logs in for the first time, the SDK will show a real-name verification popup for players to authorize the game to access their TapTap real-name information or input their identity information. After successful authentication, subsequent calls to the authentication interface with the same userIdentifier (unique identifier) will directly receive the result of the first-time authentication without triggering a popup.
```

2023-06-27 09:56 UTC, fuchenshi commented on i18n/en/docusaurus-plugin-content-docs/current/sdk/tapdb/faq/tran.mdx
> +### Q：After reporting the Custom Event, no data can be found in the backend?
```suggestion
### Q：After reporting the Custom Event, no data can be found in the backend.
```

2023-06-27 09:56 UTC, fuchenshi commented on i18n/en/docusaurus-plugin-content-docs/current/sdk/tds-gift/faq.mdx
> +sidebar_label:  Asked Questions
```suggestion
title:  FAQ
sidebar_label:  FAQ
```

2023-06-27 09:56 UTC, fuchenshi commented on i18n/en/docusaurus-plugin-content-docs/current/sdk/tds-gift/faq.mdx
> +A: No. With secondary checks enabled, the redemption system will send requests to the interface you configured on the Developer Center.
这部分和下面重复了。

2023-06-27 09:56 UTC, fuchenshi commented on i18n/en/docusaurus-plugin-content-docs/current/sdk/tds-gift/faq.mdx
> +The current maximum version gift package time is 2038-01-19 11:14:07.
```suggestion
The current maximum gift package time is 2038-01-19 11:14:07.
```

2023-06-28 03:06 UTC, fuchenshi requested changes
另外还有很多之前提的问题没有处理。

2023-06-28 03:06 UTC, fuchenshi commented on i18n/en/docusaurus-plugin-content-docs/current/sdk/start/faq.mdx
> -Thus, a user's unique identifier should be ensured for uniqueness.
这里似乎多删了一行？

2023-06-28 08:07 UTC, fuchenshi approved these changes

2023-06-28 08:07 UTC, merged