Dev other2other
taptap/tds-docs pull request #610
Opened 2023-07-16 02:57 UTC by caosir520

文档中其它改成其他

2023-07-20 02:56 UTC, fuchenshi requested changes

2023-07-20 02:56 UTC, fuchenshi commented on README.md
> +如果不想文档出现在侧边栏，则可以放在「一级导航」同级，其它文档可以通过[链接到其它文档](#链接到其它文档)进行跳转，但此时目标页将不会显示侧边栏。这些文档需要在 YAML header 指定 `slug`，以免未来移动位置后 URL 改变；还需要指定 `noindex`，这样文档不会被文档搜索系统收录。
这里（以及其他一些地方）为什么把「其他」改成了「其它」？

2023-07-21 07:58 UTC, caosir520 commented on README.md
> +如果不想文档出现在侧边栏，则可以放在「一级导航」同级，其它文档可以通过[链接到其它文档](#链接到其它文档)进行跳转，但此时目标页将不会显示侧边栏。这些文档需要在 YAML header 指定 `slug`，以免未来移动位置后 URL 改变；还需要指定 `noindex`，这样文档不会被文档搜索系统收录。
我看懂了，
一个其他->其它的修改 这个提交里面写的，然后我本地暂存了，这次然后这次提交就被一起提交上去了。我撤回这个提交就好了

2023-07-21 08:12 UTC, fuchenshi approved these changes

2023-07-21 08:12 UTC, merged