Fq 2023 07
taptap/tds-docs pull request #632
Opened 2023-08-02 06:43 UTC by caosir520

2023-08-09 09:45 UTC, fuchenshi requested changes

2023-08-09 09:45 UTC, fuchenshi commented on docs/sdk/taptap-login/faq.mdx
> +### 玩家长时间未登陆游戏 TapLoginHelper.getCurrentProfile().getOpenid() 获取不到 Openid 的问题 ？
```suggestion
### 玩家长时间未登录游戏，TapLoginHelper.getCurrentProfile().getOpenid() 获取不到 openid
```

2023-08-09 09:45 UTC, fuchenshi commented on docs/sdk/taptap-login/faq.mdx
> +TapTap 登录的授权信息会在玩家 30 天没打开过游戏（没有触发初始化）的前提下进游戏时会触发授权过期并自动清除相关数据。可以监听 Openid 值如果被清空了再走一遍[初始化](/sdk/taptap-login/guide/start/#sdk-初始化)流程，重新登陆，Openid 值重新登陆是不会改变的。
这一段写得不是很通顺。

2023-08-09 09:50 UTC, WatchMan-Wang commented on docs/sdk/taptap-login/faq.mdx
> +TapTap 登录的授权信息会在玩家 30 天没打开过游戏（没有触发初始化）的前提下进游戏时会触发授权过期并自动清除相关数据。可以监听 Openid 值如果被清空了再走一遍[初始化](/sdk/taptap-login/guide/start/#sdk-初始化)流程，重新登陆，Openid 值重新登陆是不会改变的。
注意是登录而不是登陆。

2023-08-10 11:57 UTC, caosir520 commented on docs/sdk/taptap-login/faq.mdx
> +TapTap 登录的授权信息会在玩家 30 天没打开过游戏（没有触发初始化）的前提下进游戏时会触发授权过期并自动清除相关数据。可以监听 Openid 值如果被清空了再走一遍[初始化](/sdk/taptap-login/guide/start/#sdk-初始化)流程，重新登陆，Openid 值重新登陆是不会改变的。
已修改，看看这么表述是否可以

2023-08-11 01:01 UTC, fuchenshi commented on docs/sdk/taptap-login/faq.mdx
> +TapTap 登录的授权信息会在玩家 30 天没打开过游戏（没有触发初始化）的前提下进游戏时会触发授权过期并自动清除相关数据。可以监听 Openid 值如果被清空了再走一遍[初始化](/sdk/taptap-login/guide/start/#sdk-初始化)流程，重新登陆，Openid 值重新登陆是不会改变的。
还是不太通顺。TDS 的[《中文文案风格指南》](https://blog.taptap.dev/pages/chinese-copywriting-guide)中提到：

> 请在检查中把对表达意思没有明显作用的字、词、句删除，在不影响表达效果的前提下把文案长度减到最短。

可以试着按照这条指引再调整一下，把所有多余的字词都删掉。这样也有助于提升句子的通顺程度。

2023-08-11 01:06 UTC, fuchenshi requested changes

2023-08-11 01:06 UTC, fuchenshi commented on docs/sdk/taptap-login/faq.mdx
> +在使用 TapTap 登录中，如果玩家连续 30 天未打开游戏的情况，当玩家再次进入游戏时自动触发授权过期机制，并同时清除授权信息和用户信息。
```suggestion
对于使用 TapTap 登录游戏的玩家，如果玩家连续 30 天未打开游戏，当玩家再次进入游戏时，SDK 会自动触发授权过期机制，并同时清除授权信息和用户信息。
```

2023-08-11 01:06 UTC, fuchenshi commented on docs/sdk/taptap-login/faq.mdx
> +您可以通过监测 Openid 值是否被清空，来判断是否需要重新执行[初始化](/sdk/taptap-login/guide/start/#sdk-初始化)流程，从而重新进行登录。
感觉 `Openid` 的大小写不太对，麻烦再核对一下。

2023-08-21 05:48 UTC, closed without merging

2023-08-21 05:53 UTC, fuchenshi commented
这个 PR 为什么关闭了？

2023-08-21 05:55 UTC, caosir520 commented
我需要重新提交下，这个pr一直没喝，和我另外一个 pr 有冲突了，所以我需要处理下