Engine faq
taptap/tds-docs pull request #643
Opened 2023-08-11 02:52 UTC by caosir520

2023-08-11 03:07 UTC, caosir520 commented
[增加了云引擎的绑定项目的说明](https://github.com/taptap/tds-docs/pull/643/commits/ed47205fddeda85aeb8563ddc56cf4bbe8342f7c)

2023-08-31 09:04 UTC, fuchenshi requested changes

2023-08-31 09:04 UTC, fuchenshi commented on docs/sdk/engine/faq.mdx
> +可以检查上传的服务的端口是不是 3000 ，健康检查主要是获取 3000 端口的信息所以服务提供的端口和健康检查检测端口需保持一致。
这段话的目标读者是谁？是已经成功部署应用但是在应用运行过程中遇到报错的开发者，还是部署应用过程中遇到报错的开发者，或是两者都有？第一句说「云引擎的管理系统会每隔几分钟检查所有实例的工作状态」，又说「如果还是找不到的话就会部署失败」。「每隔几分钟检查」暗示着应用已经部署成功，而已经部署成功的应用为什么会「部署失败」？另外这里的「找不到」具体指的是找不到什么？

2023-09-08 01:36 UTC, fuchenshi requested changes

2023-09-08 01:36 UTC, fuchenshi commented on docs/sdk/engine/faq.mdx
> +云引擎的管理系统会每隔几分钟检查所有实例的工作状态（通过 HTTP 检查，详见具体运行环境文档的健康检查小节），
```suggestion
云引擎的管理系统会每隔几分钟检查所有实例的工作状态（通过 HTTP 检查，详见具体运行环境文档的「健康检查」小节），
```

2023-09-08 01:36 UTC, fuchenshi commented on docs/sdk/engine/faq.mdx
> +在云引擎部署过程中会检测应用的 3000 端口是否提供了 HTTP 服务，所以请保证应用至少暴露 3000 端口。
```suggestion
云引擎在部署过程中会检测应用的 3000 端口是否提供了 HTTP 服务，所以请保证应用至少暴露了 3000 端口。
```

2023-09-08 02:28 UTC, fuchenshi approved these changes

2023-09-08 02:28 UTC, merged