更新 ReleaseNote 组件
taptap/tds-docs pull request #697
Opened 2023-09-13 02:30 UTC by yuwenjian

2023-09-13 03:49 UTC, fuchenshi requested changes

2023-09-13 03:49 UTC, fuchenshi commented on package.json
> +    "leancloud-storage": "^4.15.0",
这个好像没有在任何地方用到？

2023-09-13 03:52 UTC, fuchenshi requested changes
另外如果是自己编写一个新的组件，而不是修改已有的组件，那么代码通常是放在 `src/docComponents` 里，而不是 `src/theme`。

2023-09-13 03:54 UTC, fuchenshi requested changes

2023-09-13 03:54 UTC, fuchenshi commented on src/theme/ReleaseNote/api/index.tsx
> +  return ajax('https://taptap.leanapp.cn/releases/find/content', { sdkPlugName, sdkName }, 'GET');
这个 API 有相关文档或背后项目的代码么？

2023-09-13 03:58 UTC, yuwenjian commented on src/theme/ReleaseNote/api/index.tsx
> +  return ajax('https://taptap.leanapp.cn/releases/find/content', { sdkPlugName, sdkName }, 'GET');
这是我写的一个服务端接口，部署在云引擎

2023-09-13 04:00 UTC, yuwenjian commented on src/theme/ReleaseNote/api/index.tsx
> +  return ajax('https://taptap.leanapp.cn/releases/find/content', { sdkPlugName, sdkName }, 'GET');
```
# coding: utf-8

from flask import Flask, request
from flask_sockets import Sockets
from flask_cors import CORS, cross_origin


from views.ReleaseTool import updateFileContent, findContent

app = Flask(__name__)
sockets = Sockets(app)
cors = CORS(app)



@app.route('/releases/unity', methods=['POST'])
def webhookUnity():
    file_content = request.get_data(as_text=True)
    updateFileContent(file_content, "unity", "all")

    return 'unity success!!', 200


@app.route('/releases/android', methods=['POST'])
def webhookAndroid():
    file_content = request.get_data(as_text=True)
    updateFileContent(file_content, "android", "all")

    return 'android success!!', 200


@app.route('/releases/ios', methods=['POST'])
def webhookiOS():
    file_content = request.get_data(as_text=True)
    updateFileContent(file_content, "ios", "all")

    return 'iOS success!!', 200


@app.route('/releases/ue4', methods=['POST'])
def webhookUE():
    file_content = request.get_data(as_text=True)
    updateFileContent(file_content, "ue4", "all")

    return 'UE4 success!!', 200


@app.route('/releases/find/content', methods=['GET'])
@cross_origin()
def findReleaseContent():
    sdkPlugName = request.args.get("sdkPlugName")
    sdkName = request.args.get("sdkName")
    result = findContent(sdkPlugName, sdkName)

    return result



```

2023-09-13 04:02 UTC, yuwenjian commented on package.json
> +    "leancloud-storage": "^4.15.0",
嗯嗯，一开始准备使用 SDK 直接查的，但是想到初始化会在项目中显示 appid 等应用信息，后来就写了接口去查，这个库我给他删掉吧

2023-09-13 06:12 UTC, fuchenshi commented on package.json
> +    "leancloud-storage": "^4.15.0",
如果后端的权限配置得合理，App ID 等信息是可以暴露出来的。

2023-09-14 02:39 UTC, fuchenshi approved these changes

2023-09-14 02:40 UTC, merged