feat: add push callback usage guide
taptap/tds-docs pull request #71
Opened 2022-03-08 06:04 UTC by liuchong

1. Third-party vendor settings
2. Statistics with TapDB guide

2022-03-08 11:20 UTC, weakish requested changes

2022-03-08 11:20 UTC, weakish commented on docs/sdk/push/guide/callback-vendor.md
> +    <p align="center" width="50%"><img src="./hms1.png" /></p>
图片都需要放在 `/static/img` 目录下，引用时需要使用 `![example](/img/example.png`，否则无法正常显示。

2022-03-08 11:20 UTC, weakish commented on docs/sdk/push/guide/callback-vendor.md
> +    配置完成后，在给魅族设备发送推送时就会启用回调统计功能，您可以查询回调统计数据来观察推送情况。如果您不小心将地址配置错了，那么发送推送时魅族平台会返回“回执地址不存在，请在推送平台配置”的错误，您通过我们的控制台看到这个错误，以便及时发现并修改。
```suggestion
    配置完成后，在给魅族设备发送推送时就会启用回调统计功能，您可以查询回调统计数据来观察推送情况。如果您不小心将地址配置错了，那么发送推送时魅族平台会返回“回执地址不存在，请在推送平台配置”的错误，您通过我们的控制台看到这个错误，以便及时发现并修改。
```

按文案风格，引号需使用直角引号「、」

2022-03-08 12:29 UTC, liuchong commented on docs/sdk/push/guide/callback-vendor.md
> +    -   HTTPS 证书：通过命令 “openssl s\_client -connect callback.tds1.tapapis.cn:443” 获取。以 Linux 平台命令为例，运行命令：
咦，这里是生成的 😂

2022-03-08 12:31 UTC, liuchong commented on docs/sdk/push/guide/callback-vendor.md
> +    certifs.pem 文件就是您要的内容，将其内容贴到 HTTPS 证书文本输入框中即可。
好，我改一下。那种我点一下直接合并的评论，是怎么弄的？我想直接这么改 🌚

2022-03-08 12:35 UTC, weakish commented on docs/sdk/push/guide/callback-vendor.md
> +    certifs.pem 文件就是您要的内容，将其内容贴到 HTTPS 证书文本输入框中即可。
![image](https://user-images.githubusercontent.com/114114/157239200-3674ce62-4d55-44d5-85ad-c38fe939795d.png)

https://docs.github.com/cn/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request

不过像这个因为有多处「您」需要批量替换，可能还是在本地改更方便。

2022-03-09 05:29 UTC, kylinbin commented on docs/sdk/push/guide/callback-vendor.md
> +1.  登录华为终端开发者控制台：<https://developer.huawei.com/consumer/cn/console，进入> PUSH 服务模块后选择要配置的项目。
```suggestion
1.  登录[华为终端开发者控制台](https://developer.huawei.com/consumer/cn/console)，进入 PUSH 服务模块后选择要配置的项目。
```

2022-03-09 05:35 UTC, kylinbin commented on docs/sdk/push/guide/statistics_tapdb.md
> +btitle: 推送消息效果统计 TapDB 使用指引
```suggestion
title: 推送消息效果统计 TapDB 使用指引
```

2022-03-09 05:38 UTC, kylinbin commented on docs/sdk/push/guide/callback-vendor.md
> +1.  登录魅族推送平台控制台：<http://push.meizu.com/> ，选择正确的应用点击 [打开应用] 进入应用配置界面。
```suggestion
1.  登录[魅族推送平台控制台](http://push.meizu.com/) ，选择正确的应用点击 **打开应用** 进入应用配置界面。
```

2022-03-09 06:06 UTC, weakish approved these changes

2022-03-09 06:06 UTC, weakish commented on docs/sdk/push/guide/statistics_tapdb.md
> +1.  推送通知送达：该事件用来表示推送消息被用户设备成功接收，「推送通知送达」是它的显示名，它的事件名是「push_notification_received」。
```suggestion
1.  推送通知送达：该事件用来表示推送消息被用户设备成功接收，「推送通知送达」是它的显示名，它的事件名是`push_notification_received`。
```

2022-03-09 06:06 UTC, weakish commented on docs/sdk/push/guide/statistics_tapdb.md
> +2.  推送通知点击：该事件用来表示推送消息上的用户点击事件，「推送通知点击」是它的显示名，它的事件名是「push_notification_clicked」。
```suggestion
2.  推送通知点击：该事件用来表示推送消息上的用户点击事件，「推送通知点击」是它的显示名，它的事件名是`push_notification_clicked`。
```

2022-03-09 06:06 UTC, weakish commented on docs/sdk/push/guide/statistics_tapdb.md
> +    1.  推送送达时间：表示一次推送送达事件发生的时间，属性名是「push_received_at」。
```suggestion
    1.  推送送达时间：表示一次推送送达事件发生的时间，属性名是 `push_received_at`。
```

2022-03-09 06:06 UTC, weakish commented on docs/sdk/push/guide/statistics_tapdb.md
> +    2.  推送点击时间：表示一次推送点击事件发生的事件，属性名是「push_clicked_at」。
```suggestion
    2.  推送点击时间：表示一次推送点击事件发生的事件，属性名是 `push_clicked_at`。
```

2022-03-09 06:06 UTC, weakish commented on docs/sdk/push/guide/statistics_tapdb.md
> +    3.  推送服务的 installationId：顾名思义就是在推送服务中设备记录的的 installationId，属性名是「push_installation_id」。
```suggestion
    3.  推送服务的 installationId：顾名思义就是在推送服务中设备记录的的 installationId，属性名是`push_installation_id`。
```

2022-03-09 06:06 UTC, weakish commented on docs/sdk/push/guide/statistics_tapdb.md
> +    4.  推送通知 ID：表示使用推送服务发送推送时的 notificationId，属性名是「push_notification_id」。
```suggestion
    4.  推送通知 ID：表示使用推送服务发送推送时的 notificationId，属性名是 `push_notification_id`。
```

2022-03-09 06:06 UTC, weakish commented on docs/sdk/push/guide/statistics_tapdb.md
> +    5.  推送第三方厂商类型：表示该 Android 设备使用的是第三方厂商平台，比如华为、小米等，其值对应于推送设备记录中的 vendor 字段的小写形式，属性名是「push_vendor」。
```suggestion
    5.  推送第三方厂商类型：表示该 Android 设备使用的是第三方厂商平台，比如华为、小米等，其值对应于推送设备记录中的 vendor 字段的小写形式，属性名是 `push_vendor`。
```

2022-03-09 06:06 UTC, weakish commented on docs/sdk/push/guide/statistics_tapdb.md
> +    1.  设备 ID：SDK 在初始化时，将为该终端生成唯一的 ID，我们称之为设备 ID，属性名是「device_id」，注意他的显示名是「激活时设备 ID」。
```suggestion
    1.  设备 ID：SDK 在初始化时，将为该终端生成唯一的 ID，我们称之为设备 ID，属性名是 `device_id`，注意他的显示名是「激活时设备 ID」。
```

2022-03-09 11:06 UTC, merged