fix 老的 LC 文档地址失效并清除更换成新的 LC 文档地址
taptap/tds-docs pull request #794
Opened 2023-11-09 09:09 UTC by caosir520

2023-11-09 09:31 UTC, fuchenshi requested changes

2023-11-09 09:31 UTC, fuchenshi commented on .ci/leancloud/zh-Hans/sdk/start/dashboard-guide.mdx
> +**Play** 包括[多人在线对战](/sdk/multiplayer/features/)和[排行榜](https://docs.leancloud.app/sdk/leaderboard/features/l)服务。
```suggestion
**Play** 包括[多人在线对战](/sdk/multiplayer/features/)和[排行榜](/sdk/leaderboard/features/)服务。
```

2023-11-09 09:31 UTC, fuchenshi commented on .ci/leancloud/en/sdk/im/guide/systemconv.mdx
> +开发者可以利用这两个 Hook 函数，结合 LeanCache 来完成一组客户端实时状态查询的 endpoint，具体可以参考文档[《即时通讯中的在线状态查询》](https://docs.leancloud.app/sdk/im/best-practice/realtime-guide-onoff-status/)。
```suggestion
开发者可以利用这两个 Hook 函数，结合 LeanCache 来完成一组客户端实时状态查询的 endpoint，具体可以参考文档[《即时通讯中的在线状态查询》](/sdk/im/best-practice/realtime-guide-onoff-status/)。
```

2023-11-09 09:31 UTC, fuchenshi commented on .ci/leancloud/en/sdk/im/guide/systemconv.mdx
> +[《即时通讯中的在线状态查询》](https://docs.leancloud.app/sdk/im/best-practice/realtime-guide-onoff-status/)提供了完整的 Node.js 示例（包括 LeanCache 连接，久未上线的客户端清理，配套的返回在线状态的云函数，以及如何在客户端调用），可以参考。
```suggestion
[《即时通讯中的在线状态查询》](/sdk/im/best-practice/realtime-guide-onoff-status/)提供了完整的 Node.js 示例（包括 LeanCache 连接，久未上线的客户端清理，配套的返回在线状态的云函数，以及如何在客户端调用），可以参考。
```

2023-11-09 09:31 UTC, fuchenshi commented on docs/sdk/domain/guide.mdx
> +请参考 [即时通讯开发指南](https://developer.taptap.cn/docs/sdk/im/guide/overview/) 配置。
```suggestion
请参考 [即时通讯开发指南](/sdk/im/guide/overview/) 配置。
```

2023-11-09 09:31 UTC, fuchenshi commented on docs/sdk/im/guide/systemconv.mdx
> +开发者可以利用这两个 Hook 函数，结合 LeanCache 来完成一组客户端实时状态查询的 endpoint，具体可以参考文档[《即时通讯中的在线状态查询》](https://docs.leancloud.app/sdk/im/best-practice/realtime-guide-onoff-status/)。
```suggestion
开发者可以利用这两个 Hook 函数，结合 LeanCache 来完成一组客户端实时状态查询的 endpoint，具体可以参考文档[《即时通讯中的在线状态查询》](/sdk/im/best-practice/realtime-guide-onoff-status/)。
```

2023-11-09 09:31 UTC, fuchenshi commented on docs/sdk/im/guide/systemconv.mdx
> +[《即时通讯中的在线状态查询》](https://docs.leancloud.app/sdk/im/best-practice/realtime-guide-onoff-status/)提供了完整的 Node.js 示例（包括 LeanCache 连接，久未上线的客户端清理，配套的返回在线状态的云函数，以及如何在客户端调用），可以参考。
```suggestion
[《即时通讯中的在线状态查询》](/sdk/im/best-practice/realtime-guide-onoff-status/)提供了完整的 Node.js 示例（包括 LeanCache 连接，久未上线的客户端清理，配套的返回在线状态的云函数，以及如何在客户端调用），可以参考。
```

2023-11-09 09:31 UTC, fuchenshi commented on i18n/en/docusaurus-plugin-content-docs/current/sdk/authentication/guide.mdx
> +For each given object, you can specify which users are allowed to read it and which are allowed to modify it. To support this type of security, each object has an access control list implemented by a
```suggestion
For each given object, you can specify which users are allowed to read it and which are allowed to modify it. To support this type of security, each object has an access control list implemented by an `ACL` object. More details can be found in [ACL Guide](/sdk/storage/guide/acl/).
```

2023-11-09 09:31 UTC, fuchenshi commented on i18n/en/docusaurus-plugin-content-docs/current/sdk/engine/_partials/functions-introduction.mdx
> +Cloud Functions lets you run backend code on the cloud in response to various types of events. It is supported by our client-side SDKs and can automatically serialize objects that have the data types
```suggestion
Cloud Functions lets you run backend code on the cloud in response to various types of events. It is supported by our client-side SDKs and can automatically serialize objects that have the data types provided by our <Conditional brand="tds">[Data Storage](/sdk/storage/features)</Conditional><Conditional brand="leancloud">[Data Storage](/sdk/storage/overview/)</Conditional> service.
```

2023-11-09 09:31 UTC, fuchenshi commented on i18n/en/docusaurus-plugin-content-docs/current/sdk/engine/faq.mdx
> +On top of this, you can choose to integrate the Cloud Engine SDK into your program, which gives your program access to functions like Cloud Functions and hooks. Cloud Functions is designed to work pe
```suggestion
On top of this, you can choose to integrate the Cloud Engine SDK into your program, which gives your program access to functions like Cloud Functions and hooks. Cloud Functions is designed to work perfectly with our <Conditional brand="tds">[Data Storage](/sdk/storage/features)</Conditional><Conditional brand="leancloud">[Data Storage](/sdk/storage/overview/)</Conditional> service. If you’re already using the Data Storage service, you’ll find it easy to get started with Cloud Functions.
```

2023-11-09 09:31 UTC, fuchenshi commented on i18n/en/docusaurus-plugin-content-docs/current/sdk/engine/functions/sdk.mdx
> +The Cloud Engine SDKs for most of the runtime environments are based on the <Conditional brand="tds">[Data Storage](/sdk/storage/features)</Conditional><Conditional brand="leancloud">[Data Storage](h
```suggestion
The Cloud Engine SDKs for most of the runtime environments are based on the <Conditional brand="tds">[Data Storage](/sdk/storage/features)</Conditional><Conditional brand="leancloud">[Data Storage](/sdk/storage/overview/)</Conditional> SDK, offering additional features that support Cloud Functions and hooks. With the Cloud Engine SDK, you can easily build backend apps that can be deployed to Cloud Engine.
```

2023-11-09 09:31 UTC, fuchenshi commented on i18n/en/docusaurus-plugin-content-docs/current/sdk/engine/functions/sdk.mdx
> +Once you have integrated the SDK, you will be able to access the <Conditional brand="tds">[Data Storage](/sdk/storage/features)</Conditional><Conditional brand="leancloud">[Data Storage](https://docs
```suggestion
Once you have integrated the SDK, you will be able to access the <Conditional brand="tds">[Data Storage](/sdk/storage/features)</Conditional><Conditional brand="leancloud">[Data Storage](/sdk/storage/overview/)</Conditional> service from Cloud Engine to store data. See the articles for Data Storage SDKs for more information.
```

2023-11-09 09:31 UTC, fuchenshi commented on i18n/en/docusaurus-plugin-content-docs/current/sdk/engine/overview.mdx
> +Cloud Functions lets you run backend code on the cloud in response to various types of events. It automatically serializes objects that have the data types provided by our <Conditional brand="tds">[D
```suggestion
Cloud Functions lets you run backend code on the cloud in response to various types of events. It automatically serializes objects that have the data types provided by our <Conditional brand="tds">[Data Storage](/sdk/storage/features)</Conditional><Conditional brand="leancloud">[Data Storage](/sdk/storage/overview/)</Conditional> service and is supported by our client-side SDKs. Hooks allows you to trigger custom logics or perform additional permission checks when there are objects created, updated, or deleted in the Data Storage service, users logged in or verified, or messages sent, conversations created, or clients logged in or logged out in the Instant Messaging service.
```

2023-11-09 09:31 UTC, fuchenshi commented on i18n/en/docusaurus-plugin-content-docs/current/sdk/engine/overview.mdx
> +Cloud Engine hosts a collection of popular database management systems that you can use as alternatives to the <Conditional brand="tds">[Data Storage](/sdk/storage/features)</Conditional><Conditional
```suggestion
Cloud Engine hosts a collection of popular database management systems that you can use as alternatives to the <Conditional brand="tds">[Data Storage](/sdk/storage/features)</Conditional><Conditional brand="leancloud">[Data Storage](/sdk/storage/overview/)</Conditional> service:
```

2023-11-09 09:31 UTC, fuchenshi commented on i18n/en/docusaurus-plugin-content-docs/current/sdk/engine/platform.mdx
> +Cloud Engine is primarily optimized for hosting stateless HTTP services. Although your application has access to the disk, there’s no guarantee that the disk will keep the files created by your appli
```suggestion
Cloud Engine is primarily optimized for hosting stateless HTTP services. Although your application has access to the disk, there’s no guarantee that the disk will keep the files created by your application persistently. For long-term data storage, use the <Conditional brand="tds">[Data Storage](/sdk/storage/features)</Conditional><Conditional brand="leancloud">[Data Storage](/sdk/storage/overview/)</Conditional> service or LeanDB’s hosted [Redis](/sdk/engine/database/redis/), [MongoDB](/sdk/engine/database/mongo/), and [Elasticsearch](/sdk/engine/database/es/).
```

2023-11-09 09:31 UTC, fuchenshi commented on i18n/en/docusaurus-plugin-content-docs/current/sdk/storage/dotnet-guide/dotnet.mdx
> +Removing data from the cloud should always be dealt with great caution as it may lead to non-recoverable data loss. We strongly advise that you read [ACL Guide](https://developer.taptap.cn/docs/en/sd
```suggestion
Removing data from the cloud should always be dealt with great caution as it may lead to non-recoverable data loss. We strongly advise that you read [ACL Guide](/sdk/storage/guide/acl/) to understand the risks thoroughly. You should also consider implementing class-level, object-level, and field-level permissions for your classes in the cloud to guard against unauthorized data operations.
```

2023-11-09 09:31 UTC, fuchenshi commented on i18n/en/docusaurus-plugin-content-docs/current/sdk/storage/dotnet-guide/dotnet.mdx
> +As your app grows in scope and user base, you may find yourself needing more coarse-grained control over access to pieces of your data than user-linked ACLs can provide. To address this requirement,
```suggestion
As your app grows in scope and user base, you may find yourself needing more coarse-grained control over access to pieces of your data than user-linked ACLs can provide. To address this requirement, we support a form of role-based access control. Check the detailed [ACL Guide](/sdk/storage/guide/acl/) to learn how to set it up for your objects.
```

2023-11-09 09:31 UTC, fuchenshi commented on i18n/en/docusaurus-plugin-content-docs/current/sdk/storage/java-guide/java.mdx
> +Removing data from the cloud should always be dealt with great caution as it may lead to non-recoverable data loss. We strongly advise that you read [ACL Guide](https://developer.taptap.cn/docs/en/sd
```suggestion
Removing data from the cloud should always be dealt with great caution as it may lead to non-recoverable data loss. We strongly advise that you read [ACL Guide](/sdk/storage/guide/acl/) to understand the risks thoroughly. You should also consider implementing class-level, object-level, and field-level permissions for your classes in the cloud to guard against unauthorized data operations.
```

2023-11-09 09:31 UTC, fuchenshi commented on i18n/en/docusaurus-plugin-content-docs/current/sdk/storage/java-guide/java.mdx
> +As your app grows in scope and user base, you may find yourself needing more coarse-grained control over access to pieces of your data than user-linked ACLs can provide. To address this requirement,
```suggestion
As your app grows in scope and user base, you may find yourself needing more coarse-grained control over access to pieces of your data than user-linked ACLs can provide. To address this requirement, we support a form of role-based access control. Check the detailed [ACL Guide](/sdk/storage/guide/acl/) to learn how to set it up for your objects.
```

2023-11-09 09:31 UTC, fuchenshi commented on i18n/en/docusaurus-plugin-content-docs/current/sdk/storage/objc-guide/objc.mdx
> +Removing data from the cloud should always be dealt with great caution as it may lead to non-recoverable data loss. We strongly advise that you read [ACL Guide](https://developer.taptap.cn/docs/en/sd
```suggestion
Removing data from the cloud should always be dealt with great caution as it may lead to non-recoverable data loss. We strongly advise that you read [ACL Guide](/sdk/storage/guide/acl/) to understand the risks thoroughly. You should also consider implementing class-level, object-level, and field-level permissions for your classes in the cloud to guard against unauthorized data operations.
```

2023-11-09 09:31 UTC, fuchenshi commented on i18n/en/docusaurus-plugin-content-docs/current/sdk/storage/objc-guide/objc.mdx
> +As your app grows in scope and user base, you may find yourself needing more coarse-grained control over access to pieces of your data than user-linked ACLs can provide. To address this requirement,
```suggestion
As your app grows in scope and user base, you may find yourself needing more coarse-grained control over access to pieces of your data than user-linked ACLs can provide. To address this requirement, we support a form of role-based access control. Check the detailed [ACL Guide](/sdk/storage/guide/acl/) to learn how to set it up for your objects.
```

2023-11-09 09:31 UTC, fuchenshi commented on i18n/en/docusaurus-plugin-content-docs/current/sdk/storage/security.mdx
> +Please refer to [The ACL Guide](https://developer.taptap.cn/docs/en/sdk/storage/guide/acl/) for details.
```suggestion
Please refer to [The ACL Guide](/sdk/storage/guide/acl/) for details.
```

2023-11-09 09:44 UTC, caosir520 commented on docs/sdk/im/guide/systemconv.mdx
> +[《即时通讯中的在线状态查询》](/sdk/im/best-practice/realtime-guide-onoff-status/)提供了完整的 Node.js 示例（包括 LeanCache 连接，久未上线的客户端清理，配套的返回在线状态的云函数，以及如何在客户端调用），可以参考。
(/sdk/im/best-practice/realtime-guide-onoff-status/)
```suggestion
[《即时通讯中的在线状态查询》](https://docs.leancloud.app/sdk/im/best-practice/realtime-guide-onoff-status/)提供了完整的 Node.js 示例（包括 LeanCache 连接，久未上线的客户端清理，配套的返回在线状态的云函数，以及如何在客户端调用），可以参考。
```

2023-11-09 09:44 UTC, caosir520 commented on docs/sdk/im/guide/systemconv.mdx
> +[《即时通讯中的在线状态查询》](/sdk/im/best-practice/realtime-guide-onoff-status/)提供了完整的 Node.js 示例（包括 LeanCache 连接，久未上线的客户端清理，配套的返回在线状态的云函数，以及如何在客户端调用），可以参考。
在线状态查询文档 TapTap 没有，只能链接到 LC 那边

2023-11-09 09:46 UTC, caosir520 commented on .ci/leancloud/en/sdk/im/guide/systemconv.mdx
> +[《即时通讯中的在线状态查询》](/sdk/im/best-practice/realtime-guide-onoff-status/)提供了完整的 Node.js 示例（包括 LeanCache 连接，久未上线的客户端清理，配套的返回在线状态的云函数，以及如何在客户端调用），可以参考。
```suggestion
[《即时通讯中的在线状态查询》](https://docs.leancloud.app/sdk/im/best-practice/realtime-guide-onoff-status/)提供了完整的 Node.js 示例（包括 LeanCache 连接，久未上线的客户端清理，配套的返回在线状态的云函数，以及如何在客户端调用），可以参考。
```

2023-11-09 09:46 UTC, caosir520 commented on .ci/leancloud/en/sdk/im/guide/systemconv.mdx
> +[《即时通讯中的在线状态查询》](/sdk/im/best-practice/realtime-guide-onoff-status/)提供了完整的 Node.js 示例（包括 LeanCache 连接，久未上线的客户端清理，配套的返回在线状态的云函数，以及如何在客户端调用），可以参考。
在线状态查询 TapTap 文档里面没有，只能链接到 LC 那边

2023-11-09 09:46 UTC, caosir520 commented on docs/sdk/im/guide/systemconv.mdx
> +开发者可以利用这两个 Hook 函数，结合 LeanCache 来完成一组客户端实时状态查询的 endpoint，具体可以参考文档[《即时通讯中的在线状态查询》](/sdk/im/best-practice/realtime-guide-onoff-status/)。
```suggestion
开发者可以利用这两个 Hook 函数，结合 LeanCache 来完成一组客户端实时状态查询的 endpoint，具体可以参考文档[《即时通讯中的在线状态查询》](https://docs.leancloud.app/sdk/im/best-practice/realtime-guide-onoff-status/)。
```

2023-11-09 09:49 UTC, fuchenshi commented on .ci/leancloud/en/sdk/im/guide/systemconv.mdx
> +[《即时通讯中的在线状态查询》](/sdk/im/best-practice/realtime-guide-onoff-status/)提供了完整的 Node.js 示例（包括 LeanCache 连接，久未上线的客户端清理，配套的返回在线状态的云函数，以及如何在客户端调用），可以参考。
那这种就还保留完整链接吧。

2023-11-09 09:54 UTC, caosir520 commented on .ci/leancloud/en/sdk/im/guide/systemconv.mdx
> +开发者可以利用这两个 Hook 函数，结合 LeanCache 来完成一组客户端实时状态查询的 endpoint，具体可以参考文档[《即时通讯中的在线状态查询》](/sdk/im/best-practice/realtime-guide-onoff-status/)。
```suggestion
开发者可以利用这两个 Hook 函数，结合 LeanCache 来完成一组客户端实时状态查询的 endpoint，具体可以参考文档[《即时通讯中的在线状态查询》](https://docs.leancloud.app/sdk/im/best-practice/realtime-guide-onoff-status/)。
```

2023-11-09 10:08 UTC, fuchenshi requested changes
把 conflicts 处理一下吧。

2023-11-10 03:20 UTC, fuchenshi approved these changes

2023-11-10 03:20 UTC, merged